export const ITEMS = [
    {
        pk: 987,
        name: 'Book Name',
        points: 150,
        quantity: 14,
        display_img_url: 'assets/book.jpg',
        valid_until: '2024-12-31T00:00:00',
        low_quantity: 10,
      },
      {
        pk: 988,
        name: 'Grocery Gift Card',
        points: 200,
        display_img_url: 'assets/giftCard.jpg',
        quantity: 5,
        valid_until: '2024-11-30T00:00:00',
        low_quantity: 10,
      },
      {
        pk: 989,
        name: 'Electronics Discount',
        points: 500,
        display_img_url: 'assets/electronic.jpg',
        quantity: 0,
        valid_until: '2024-12-15T00:00:00',
        low_quantity: 10,
      },
      {
        pk: 990,
        name: 'Travel Voucher',
        points: 300,
        display_img_url: 'assets/travel.jpg',
        quantity: 20,
        valid_until: '2024-10-01T00:00:00',
        low_quantity: 10,
      },
      {
        pk: 991,
        name: 'Fitness Membership',
        points: 400,
        display_img_url: 'assets/fitness.jpg',
        quantity: 8,
        valid_until: '2024-09-15T00:00:00',
        low_quantity: 10,
      },
      {
        pk: 992,
        name: 'Movie Tickets',
        points: 120,
        display_img_url: 'assets/tickit.jpg',
        quantity: 15,
        valid_until: '2024-12-31T00:00:00',
        low_quantity: 10,
      },
      {
        pk: 993,
        name: 'Coffee Gift Card',
        points: 100,
        display_img_url: 'assets/cofee.jpg',
        quantity: 2,
        valid_until: '2024-08-31T00:00:00',
        low_quantity: 10,
      },
      {
        name: 'Dairy Farm $20',
        points: 2,
        quantity: 3,
        display_img_url: 'assets/dairy.jpg',
      },
      {
        name: 'Qoo10 $5',
        points: 10,
        quantity: 0,
        display_img_url: '',
      }
  ];